### PR TITLE
Update basis.py, try to fix the NaN

### PR DESCRIPTION
**Pull request by cyang31**
On my end, this part used to generate NaN values. So the current trick prevents the NaN. Please check.

### CODE REVIEW

**Comment by lucidrains** [comment]
@cyang31 oh good catch, put in a fix (just used clamp instead and also made eps configurable)

**Comment by lucidrains** [comment]
Oh! maybe this also fixes the nan issue I saw when trying to train on float32! If so, thanks!

**Comment by cyang31** [comment]
Thank you for your invaluable contribution to the open-source community!!!

**Comment by lucidrains** [comment]
oh yeah no problem!

this was already officially open sourced by the author at atomicarchitects too, just so you know

**Pull request closed without merging**
